### PR TITLE
move file failed when path is \\?\C:\ style)

### PR DESCRIPTION
**Pull request by xspeed1989**
move file failed when path is \\\\?\\C:\ style),so i trim \\\\?\\;

### CODE REVIEW

**Comment by DDoSolitary** [comment]
Some problems:

- You added <regex> to stdafx.h but forgot to remove it from main.cpp.
- I doubt if it's necessary to introduce <regex> to accomplish this task. In my opinion, normal string comparison is enough.
- The move action is not the only one that doesn't support the "\\?\" syntax. If you want to fix it, please fix it completely to avoid inconsistency in code.

(Or if you can wait, I can find some time to fix it myself in July, when the exam season is over.)

**Comment by xspeed1989** [comment]
> Some problems:
> 
> * You added <regex> to stdafx.h but forgot to remove it from main.cpp.
> * I doubt if it's necessary to introduce <regex> to accomplish this task. In my opinion, normal string comparison is enough.
> * The move action is not the only one that doesn't support the "\\?\" syntax. If you want to fix it, please fix it completely to avoid inconsistency in code.
> 
> (Or if you can wait, I can find some time to fix it myself in July, when the exam season is over.)

额 看你资料是中国人，就不用塑料英语跟你交流了，
用正则是因为我懒 ，懒得去用原始的字符串操作，哈哈哈哈 嗝

**Comment by DDoSolitary** [comment]
🤣 好的
既然pr你关了，那就等我考期结束我来修了

**Comment by xspeed1989** [comment]
> 🤣 好的
> 既然pr你关了，那就等我考期结束我来修了

哈哈 好的 反正我现在已经成功move了，慢慢来 慢慢来  好好学习 天天向上

**Comment by DDoSolitary** [comment]
Fixed in c31946041a5da1724b985944b98cee9daebec340.

**Pull request closed without merging**
