### PR TITLE
reg.cpp: check for guid format

### LINKED ISSUE #171: Couldn't get the value "DistributionName" on Windows 11
```powershell
PS C:\Users\echo\Desktop> lxrunoffline.exe install `
>> -n AOSC `
>> -d C:\files\AOSC\ `
>> -f C:\Users\echo\Downloads\aosc-os_base+nvidia_20210602_amd64.tar.xz `
>> -s
[ERROR] Couldn't get the value "DistributionName" of the registry key "Software\Microsoft\Windows\CurrentVersion\Lxss\AppxInstallerCache".
Reason: 系统找不到指定的文件。
// Reason: System could not found specific file.
```

### PR DESCRIPTION
**Pull request by Artoria2e5**
If this complies this should fix #171

### CODE REVIEW

**Comment by DDoSolitary** [comment]
Thanks. Some suggestions:

- Pass the string as const ref (`crwstr`)
- Also skip if the string is too long (`code == ERROR_MORE_DATA`)

**Comment by Artoria2e5** [comment]
I think I should really grab a compiler before I do all that...

**Comment by Artoria2e5** [comment]
Oh by the way, I don't think the thing needs a length check. The calling buffer is supposed to only be that long anyways, and I don't find the regex particularly complex.

**Comment by DDoSolitary** [comment]
I mean, as Microsoft is adding other "non-distro" subkeys under the `Lxss` key, it's possible that they add something whose name is longer than a GUID. In that case, the current code will simply throw an exception and exit immediately

https://github.com/DDoSolitary/LxRunOffline/blob/9ad255434f27c282a172ff9468d55179504a8e67/src/lib/reg.cpp#L151

This is not very ideal and we need to make it skip the subkey instead.

**Comment by Artoria2e5** [comment]
many thanks for cleaning my shit up…

**Pull request merged**
